generated_at_utc: '2025-08-14T08:32:08.752886+00:00'
manifest_version: 7.1-idempotent
validation_signature: 81ec95034c0b6b3d91f1c61f9bc330aec2761fdde4a10ad66ca7494273f77ee1
personas:
- alias: _base/bcaa-1
  title: Base Collaborative Agent
  description: No description provided.
- alias: _base/btaa-1
  title: Base Technical Analysis Agent
  description: No description provided.
- alias: _mixins/codegen-standards-1
  title: Code Generation Standards Mixin
  description: No description provided.
- alias: core/arc-1
  title: Architecture Reviewer & Consultant
  description: No description provided.
- alias: core/csa-1
  title: Collaborative Systems Architect
  description: No description provided.
- alias: core/dca-1
  title: Documentation & Content Architect
  description: No description provided.
- alias: core/dpa-1
  title: Deployment Process Architect
  description: No description provided.
- alias: core/pa-1
  title: Persona Architect
  description: A specialist meta-persona that designs, refines, and governs the entire
    persona ecosystem, focusing on prompt reliability, efficiency, and strategic growth.
- alias: core/si-1
  title: Session Initiator
  description: No description provided.
- alias: domains/finance/ada-1
  title: API Contract Architect
  description: No description provided.
- alias: domains/trading/qtsa-1
  title: Quantitative Strategy Analyst
  description: No description provided.
- alias: patterns/adr-1
  title: Architectural Decision Analyst
  description: No description provided.
- alias: patterns/bpr-1
  title: Best Practices Reviewer
  description: No description provided.
- alias: patterns/da-1
  title: Debugging Analyst
  description: No description provided.
- alias: patterns/pba-1
  title: Performance Bottleneck Analyst
  description: No description provided.
- alias: patterns/qsa-1
  title: Quality Strategy Architect
  description: No description provided.
- alias: patterns/sia-1
  title: Systems Integrity Analyst
  description: No description provided.
- alias: patterns/sva-1
  title: Security Vulnerability Auditor
  description: No description provided.
- alias: patterns/tae-1
  title: Test Automation Engineer
  description: No description provided.
- alias: utility/alignment-checker
  title: Mandate Alignment Checker
  description: No description provided.
- alias: utility/jan-1
  title: Project Janitor
  description: No description provided.
