generated_at_utc: '2025-08-17T02:43:48.491281+00:00'
manifest_version: 7.3-central-validator
validation_signature: fec8c447302076ee6b585e0e840c55a1454fd3c09b0a18483bc9d04c5059fe81
personas:
- alias: core/amd-1
  title: Agent Manual Documenter
  description: Analyzes a project's configuration files to generate a concise AGENTS.md
    manual for consumption by other AI agents.
- alias: core/arc-1
  title: Architecture Reviewer & Consultant
  description: Performs rigorous, evidence-based audits to identify architectural
    deviations and provide actionable recommendations.
- alias: core/cia-1
  title: Contextual Intelligence Analyst
  description: Automatically discovers and injects project-specific context from a
    root AGENTS.md file.
- alias: core/csa-1
  title: Collaborative Systems Architect
  description: Designs new systems or refactors existing ones, ensuring all changes
    are harmonious with the established architecture.
- alias: core/dca-1
  title: Documentation & Content Architect
  description: Creates clear, accurate, and user-centric documentation based on the
    system's technical artifacts.
- alias: core/dpa-1
  title: Deployment Process Architect
  description: Provides a comprehensive, risk-mitigated deployment plan for production
    releases.
- alias: core/ia-1
  title: Integration Architect
  description: Translates an internal execution plan into a validated manifest for
    an external agent like Jules.
- alias: core/pa-1
  title: Persona Architect
  description: A specialist meta-persona that designs, refines, and governs the entire
    persona ecosystem, focusing on prompt reliability, efficiency, and strategic growth.
- alias: core/pmo-1
  title: Project Manager & Orchestrator
  description: Manages a multi-stage software development project by maintaining a
    state file and orchestrating other specialist personas.
- alias: core/si-1
  title: Session Initiator
  description: Analyzes a user's high-level goal and selects the most appropriate
    specialist agent to perform the task.
- alias: domains/finance/ada-1
  title: API Contract Architect
  description: Designs API contracts for financial services, focusing on REST and
    OpenAPI standards.
- alias: domains/trading/qtsa-1
  title: Quantitative Strategy Analyst
  description: Guides the development of formal, testable trading strategy blueprints
    from high-level concepts.
- alias: patterns/adr-1
  title: Architectural Decision Analyst
  description: Analyzes technical problems and generates structured Architectural
    Decision Records (ADRs) to document key decisions.
- alias: patterns/bpr-1
  title: Best Practices Reviewer
  description: Acts as a senior peer reviewer for code quality, style, and adherence
    to established best practices.
- alias: patterns/da-1
  title: Debugging Analyst
  description: Diagnoses the root cause of bugs from error reports, stack traces,
    and relevant source code.
- alias: patterns/pba-1
  title: Performance Bottleneck Analyst
  description: Analyzes system behavior and metrics to identify and diagnose performance
    bottlenecks.
- alias: patterns/pva-1
  title: Plan Validation Analyst
  description: A skeptical analyst that reviews a proposed tool-use plan for flaws,
    risks, and unstated assumptions.
- alias: patterns/qsa-1
  title: Quality Strategy Architect
  description: Analyzes a codebase to create a prioritized, risk-based testing plan.
- alias: patterns/sia-1
  title: Systems Integrity Analyst
  description: Audits system configurations and state to ensure they align with a
    declared 'source of truth' document.
- alias: patterns/sva-1
  title: Security Vulnerability Auditor
  description: Reviews code with an adversarial mindset to find potential security
    vulnerabilities.
- alias: patterns/tae-1
  title: Test Automation Engineer
  description: Generates automated tests (unit, integration, or end-to-end) for a
    given source code file.
- alias: utility/alignment-checker
  title: Mandate Alignment Checker
  description: Performs a semantic check to ensure a specialist's proposed plan aligns
    with the user's original mandate.
- alias: utility/jan-1
  title: Project Janitor
  description: Performs code cleanup tasks like removing comments, formatting, and
    deleting specified code blocks.
