[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my-ai-assistant"
version = "1.0.2" # Incrementing version for this packaging fix
description = "AI Assistant for Software Development"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "requests",
    "pyyaml",
    "pydantic>=2.0"
]

[project.scripts]
ai = "ai_assistant.cli:main"

# --- HATCH CONFIGURATION (Corrected) ---
[tool.hatch.build.targets.wheel]
# This tells Hatch to include both packages from the 'src' directory.
packages = ["src/ai_assistant", "src/plugins"]

[tool.hatch.build]
# This section ensures all non-code data files are included.
include = [
    "src/ai_assistant/default_config.yml",
    "src/ai_assistant/personas/**/*.md",
]