[build-system]
requires = ["setuptools>=65.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "my-ai-assistant"
version = "1.0.7"
description = "AI Assistant for Software Development"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "requests",
    "pyyaml",
    "pydantic>=2.0"
]

[project.scripts]
ai = "ai_assistant.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["ai_assistant*", "plugins*"]

[tool.setuptools.package-data]
ai_assistant = [
    "default_config.yml",
    "personas/**/*.md",
    "personas/**/*.py"
]