[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my-ai-assistant"
version = "1.0.6" # The final version for this definitive fix
description = "AI Assistant for Software Development"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "requests",
    "pyyaml",
    "pydantic>=2.0"
]

[project.scripts]
ai = "ai_assistant.cli:main"

# This section ensures all non-code data files are included in the build.
# By removing all other [tool.hatch] configuration, we allow Hatch
# to use its default, correct behavior for a src-layout.
[tool.hatch.build]
include = [
    "src/ai_assistant/default_config.yml",
    "src/ai_assistant/personas",
]